<?php echo $this->tag->form("user/signup"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>

</form>

<div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>">
    <?php echo isset($message)?$message:""; ?>
</div>

